name: Run License Tests
on:
  push:
  workflow_dispatch:
  pull_request:
    branches:
      - master
jobs:
  license_tests:
    uses: neongeckocom/.github/.github/workflows/license_tests.yml@master
    with:
      packages-exclude: '^(bs4|nvidia|bitstruct|audioread|klat-connector|chatbot-core|tqdm|dnspython).*'