# This workflow will generate a PR for changes in dev into master for a skill

name: Run Unit Tests
on:
  push:
    branches:
      - dev
      - staging
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install git+https://neondemo:${{secrets.demo_user_password}}@github.com/neongeckocom/klat-connector
        env:
          PWD: ${{secrets.demo_user_password}}
      - name: Test with pytest
        run: |
          pip install pytest pytest-timeout pytest-cov
          pytest tests/chatbot_core_tests.py --doctest-modules --junitxml=tests/test-results.xml
      - name: Upload pytest test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: tests/test-results.xml